### ISSUE TITLE
I can't see any link to use this module after installed it

### ISSUE THREAD

**Issue by badis** [humhub/humhub-modules-sms#3]
Hi ,

I have installed sms module version : 0.7.0 with HumHub version 0.20.1 and it's not working . could any one tell me how to fix it please !

**Comment by dzomb** [comment]
Me neither - not sure why.

**Comment by BastusIII** [comment]
This should be fixed by now, please check out the new version.
Problem was in reaction to the menu init event. The condition there was no longer valid and incompatible to newer humhub versions.
